### ISSUE TITLE
Provide solve-issues job as template so it become possible to override variables can ove

### ISSUE THREAD

**Issue by jcraftsman** [umans-tech/issue-solver-bots#11]
Example of desired usage

```
my-solve-issues-job:
  variables:
    AGENT: "SWE-crafter" # default agent
    DOCKER_HOST: ""
  extends: .solve-issues
```
